# Generated by Django 4.0.3 on 2022-12-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_automobilevo_sold_alter_sale_automobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.PositiveIntegerField(),
        ),
    ]
