# Generated by Django 4.0.3 on 2022-12-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_sale_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='manufacturer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='model_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='picture_url',
            field=models.URLField(null=True),
        ),
    ]
