# Generated by Django 4.0.3 on 2022-12-07 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tech',
            new_name='Technician',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='owner',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='tech',
            new_name='technician',
        ),
    ]
