# Generated by Django 4.0.3 on 2022-12-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_appointment_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='automobile',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='vip',
        ),
        migrations.AddField(
            model_name='appointment',
            name='purchased',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vin',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
