# Generated by Django 4.0.3 on 2022-12-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_remove_appointment_automobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='finished',
            new_name='complete',
        ),
    ]
